[package]
name = "subvt-notification-processor"
version = "0.13.13"
edition = "2021"
rust-version = "1.63.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2 = "0.6.2"
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
fcm = "0.9.1"
futures = "0.3.21"
futures-util = "0.3.21"
itertools = "0.10.3"
job_scheduler = "1.2.1"
lazy_static = "1.4.0"
lettre = { version = "0.10", default-features = true, features = ["tokio1-native-tls"]}
lettre_email = "0.9.4"
log = "0.4.16"
once_cell = "1.13"
redis = { version = "0.21.5", features = ["tokio-comp"] }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-telegram-bot = { path = "../subvt-telegram-bot" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tera = "1.16.0"
thiserror = "1.0"
tokio = { version = "1.20", features = ["full"] }