[package]
name = "subvt-notification-processor"
version = "0.1.3"
edition = "2021"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2 = "0.6.2"
anyhow = "1.0.56"
async-trait = "0.1.53"
chrono = "0.4.19"
fcm = "0.9.1"
frankenstein = { version = "0.12.0", default-features = false, features = ["async-http-client"] }
futures = "0.3.21"
futures-util = "0.3.21"
itertools = "0.10.3"
job_scheduler = "1.2.1"
lazy_static = "1.4.0"
lettre = { version = "0.10.0-rc.5", default-features = true, features = ["tokio1-native-tls"]}
lettre_email = "0.9.4"
log = "0.4.16"
once_cell = "1.10.0"
redis = { version = "0.21.5", features = ["tokio-comp"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tera = "1.15.0"
thiserror = "1.0"
tokio = { version = "1.17.0", features = ["full"] }