[substrate]
chain = "polkadot"
chain_display = "Polkadot"
chain_genesis_hash = "0x91B171BB158E2D3848FA23A9F1C25182FB8E20313B2C1EB49219DA7A70CE90C3"
rpc_url = "wss://rpc.polkadot.io:443"
timeout_seconds = 30
connection_timeout_seconds = 30
request_timeout_seconds = 30
network_id = 2

[block_processor]
start_block_number = 2_700_565

[onekv]
candidate_history_record_count = 5
candidate_list_endpoint = "https://polkadot.w3f.community/candidates"
candidate_details_endpoint = "https://polkadot.w3f.community/candidate/"
nominator_list_endpoint = "https://polkadot.w3f.community/nominators"
refresh_seconds = 300
request_timeout_seconds = 60