[package]
name = "subvt-block-processor"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.44"
async-lock = "2.4.0"
async-recursion = "0.3.2"
async-trait = "0.1.51"
chrono = { version = "0.4.19", default-features = true, features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.14"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.11.0", features = ["full"] }