[package]
name = "subvt-plotter"
version = "0.1.3"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
charts = "0.3.0"
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.16"
plotters = "0.3.1"
resvg = "0.22.0"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tiny-skia = "0.6.3"
usvg = "0.22.0"