[package]
name = "subvt-plotter"
version = "0.7.1"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4.19"
env_logger = "0.9.0"
format_num = "0.1.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.16"
thiserror = "1.0"
rand = "0.8.5"
resvg = "0.23.0"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
svg = "0.10.0"
tiny-skia = "0.6.5"
usvg = "0.23.0"