[package]
name = "subvt-plotter"
version = "0.1.3"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
env_logger = "0.9.0"
log = "0.4.16"
plotters = "0.3.1"
subvt-config = { path = "../subvt-config" }