services:
  subvt_network_postgres:
    container_name: subvt_network_postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=20"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "effective_cache_size=12GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=102400kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=6"
      - "-c"
      - "max_parallel_workers_per_gather=3"
      - "-c"
      - "max_parallel_workers=6"
      - "-c"
      - "max_parallel_maintenance_workers=3"
    restart: unless-stopped
    image: "helikon/subvt-network-postgres:0.1.2"
    networks:
      - kusama_network_deployment
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - subvt_network_postgres_data:/var/lib/postgresql/data
  subvt_network_redis:
    container_name: subvt_network_redis
    restart: unless-stopped
    image: "redis:6.2.6"
    command: redis-server --save "" --appendonly no
    networks:
      - kusama_network_deployment
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - subvt_network_redis_data:/data
  subvt_block_processor:
    container_name: subvt_block_processor
    restart: unless-stopped
    image: "helikon/subvt-block-processor:0.1.2"
    depends_on:
      - subvt_network_postgres
      - subvt_network_redis
    networks:
      - kusama_network_deployment
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      - SUBVT__BLOCK_PROCESSOR__START_BLOCK_NUMBER=6015486
      #- SUBVT__SUBSTRATE__RPC_URL=ws://192.168.0.101:9944
  subvt_validator_list_updater:
    container_name: subvt_validator_list_updater
    restart: unless-stopped
    image: "helikon/subvt-validator-list-updater:0.1.2"
    depends_on:
      - subvt_block_processor
    networks:
      - kusama_network_deployment
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      #- SUBVT__SUBSTRATE__RPC_URL=ws://192.168.0.101:9944
  subvt_active_validator_list_server:
    container_name: subvt_active_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-active-validator-list-server:0.1.2"
    depends_on:
      - subvt_validator_list_updater
    networks:
      - kusama_network_deployment
    ports:
      - 127.0.0.1:7889:7889
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
  subvt_inactive_validator_list_server:
    container_name: subvt_inactive_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-inactive-validator-list-server:0.1.2"
    depends_on:
      - subvt_validator_list_updater
    networks:
      - kusama_network_deployment
    ports:
      - 127.0.0.1:7890:7890
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
  subvt_validator_details_server:
    container_name: subvt_validator_details_server
    restart: unless-stopped
    image: "helikon/subvt-validator-details-server:0.1.2"
    depends_on:
      - subvt_validator_list_updater
    networks:
      - kusama_network_deployment
    ports:
      - 127.0.0.1:7891:7891
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
  subvt_network_status_updater:
    container_name: subvt_network_status_updater
    restart: unless-stopped
    image: "helikon/subvt-network-status-updater:0.1.2"
    depends_on:
      - subvt_network_redis
    networks:
      - kusama_network_deployment
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      #- SUBVT__SUBSTRATE__RPC_URL=ws://192.168.0.101:9944
  subvt_network_status_server:
    container_name: subvt_network_status_server
    restart: unless-stopped
    image: "helikon/subvt-network-status-server:0.1.2"
    depends_on:
      - subvt_network_status_updater
    networks:
      - kusama_network_deployment
    ports:
      - 127.0.0.1:7888:7888
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
  subvt_onekv_updater:
    container_name: subvt_onekv_updater
    restart: unless-stopped
    image: "helikon/subvt-onekv-updater:0.1.2"
    depends_on:
      - subvt_network_postgres
    networks:
      - kusama_network_deployment
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
  # TODO :: add telemetry processor :: gives 404
  # TODO :: add notification generator :: needs app postgres
  subvt_report_service:
    container_name: subvt_report_service
    restart: unless-stopped
    image: "helikon/subvt-report-service:0.1.2"
    depends_on:
      - subvt_network_postgres
    networks:
      - kusama_network_deployment
    ports:
      - 127.0.0.1:7900:7900
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
volumes:
  subvt_network_postgres_data:
    name: subvt_network_postgres_data
  subvt_network_redis_data:
    name: subvt_network_redis_data
networks:
  kusama_network_deployment: