[workspace]
members = [
    "subvt-app-services",
    "subvt-block-processor",
    "subvt-config",
    "subvt-live-network-status-server",
    "subvt-live-network-status-updater",
    "subvt-logging",
    "subvt-notifier",
    "subvt-onekv-updater",
    "subvt-persistence",
    "subvt-proc-macro",
    "subvt-report-services",
    "subvt-service-common",
    "subvt-substrate-client",
    "subvt-types",
    "subvt-utility",
    "subvt-validator-details-server",
    "subvt-validator-list-server",
    "subvt-validator-list-updater",
]
