[package]
name = "subvt-validator-list-updater"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-lock = "2.5.0"
async-trait = "0.1.52"
chrono = "0.4.19"
hex = "0.4"
lazy_static = "1.4.0"
log = "0.4.14"
once_cell = "1.10.0"
redis = "0.21.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.17.0", features = ["full"] }
