[substrate]
chain = "kusama"
chain_display = "Kusama"
chain_genesis_hash = "0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE"
epochs_per_era = 6
rpc_url = "wss://kusama-rpc.polkadot.io:443"
network_id = 1
token_ticker = "KSM"
token_decimals = 12

[block_processor]
# min supported for Kusama is 4_401_243, metadata v12
# first block of 2021 for Kusama is 6_015_486
start_block_number = 6_015_486

[onekv]
candidate_list_endpoint = "https://kusama.w3f.community/candidates"
candidate_details_endpoint = "https://kusama.w3f.community/candidate/"
nominator_list_endpoint = "https://kusama.w3f.community/nominators"

[notification_generator]
unclaimed_payout_check_delay_hours = 3