[package]
name = "subvt-app-service"
version = "0.3.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
actix-http = "3.0.0-rc.1"
actix-service = "2.0.2"
actix-web = "4.0.0-rc.2"
anyhow = "1.0.57"
async-trait = "0.1.53"
futures = "0.3.21"
hex = "0.4"
libsecp256k1 = "0.7.0"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10.2"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.17.0", features = ["full"] }

[dev-dependencies]
actix-rt = "2.7.0"