[package]
name = "subvt-app-service"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
actix-web = "4.0.0-beta.18"
anyhow = "1.0.52"
async-trait = "0.1.52"
config = "0.11.0"
hex = "0.4"
lazy_static = "1.4.0"
log = "0.4.14"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
subvt-config = { path = "../subvt-config" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.15.0", features = ["full"] }