[package]
name = "subvt-logging"
version = "0.14.29"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
env_logger = "0.10"
log = { workspace = true }
subvt-config = { path = "../subvt-config" }