[log]
subvt_level = "info"
other_level = "warn"

[redis]
url = "redis://subvt_network_redis:6379/"

[network_postgres]
host = "subvt_network_postgres"

[onekv]
refresh_seconds = 300

[notification_sender]
apns_is_production = true
