[package]
name = "subvt-persistence"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.53"
chrono = "0.4.19"
hex = "0.4"
log = "0.4.14"
parity-scale-codec = "2.3.1"
serde = { version = "1.0.135" }
serde_json = "1.0.75"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
sqlx = { version = "0.5.10", features = ["postgres", "runtime-tokio-rustls", "chrono"] }