[package]
name = "subvt-persistence"
version = "0.4.1"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.57"
chrono = "0.4.19"
hex = "0.4"
lazy_static = "1.4.0"
log = "0.4.16"
parity-scale-codec = "3.1.2"
redis = { version = "0.21.5", features = ["tokio-comp"] }
serde = { version = "1.0.137" }
serde_json = "1.0.81"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
sqlx = { version = "0.5.13", features = ["postgres", "runtime-tokio-rustls", "chrono"] }