[package]
name = "subvt-persistence"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
hex = "0.4"
lazy_static = "1.4.0"
log = "0.4.14"
parity-scale-codec = "3.1.2"
redis = "0.21.5"
serde = { version = "1.0.136" }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
sqlx = { version = "0.5.11", features = ["postgres", "runtime-tokio-rustls", "chrono"] }