[common]
recovery_retry_seconds = 5

[substrate]
chain = "kusama"
# Kusama    0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe
# Polkadot  0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3
chain_genesis_hash = "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
rpc_url = "wss://kusama-rpc.polkadot.io:443"
timeout_seconds = 30
connection_timeout_seconds = 30
request_timeout_seconds = 30

[log]
subvt_level = "debug"
other_level = "warn"

[rpc]
host = "127.0.0.1"
live_network_status_port = 7888
active_validator_list_port = 7889
inactive_validator_list_port = 7890
validator_details_port = 7891

[http]
host = "0.0.0.0"
report_service_port = 7900
app_service_port = 7901

[redis]
url = "redis://127.0.0.1:5432/"

[postgres]
host = "127.0.0.1"
port = 5432
username = "subvt"
password = "subvt"
database_name = "subvt"
pool_max_connections = 20

[block_processor]
# min supported for Kusama is 4401243, metadata v12
# for Polkadot it is 2005673
start_block_number = 9000000

[onekv]
candidate_list_endpoint = "https://kusama.w3f.community/candidates"
candidate_details_endpoint = "https://kusama.w3f.community/candidate/"
refresh_seconds = 10
request_timeout_seconds = 60

[report]
max_era_index_range = 100

[telemetry]
# W3F       wss://telemetry.w3f.community/feed
# Polkadot  wss://feed.telemetry.polkadot.io/feed/
websocket_url = "wss://telemetry.w3f.community/feed"
