[package]
name = "subvt-report-service"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.45"
async-trait = "0.1.51"
config = "0.11.0"
lazy_static = "1.4.0"
subvt-config = { path = "../subvt-config" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
