[package]
name = "subvt-report-service"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
actix-web = "4.0.0-rc.2"
anyhow = "1.0.53"
async-trait = "0.1.52"
config = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.17.0", features = ["full"] }