[package]
name = "subvt-report-service"
version = "0.12.2"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
actix-web = "4.1.0"
anyhow = "1.0"
async-trait = "0.1"
futures-util = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.20", features = ["full"] }