[package]
name = "subvt-report-service"
version = "0.14.23"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
actix-web = "4.1.0"
anyhow = { workspace = true }
async-trait = "0.1"
futures-util = "0.3.21"
lazy_static = { workspace = true }
log = { workspace = true }
once_cell = "1.13"
redis = { version = "0.22.1", features = ["tokio-comp"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.20", features = ["full"] }