swagger: "2.0"
info:
  description: "SubVT report service endpoints."
  version: "0.1.0"
  title: "SubVT Report Service"
  termsOfService: "https://subvt-test.helikon.io"
  contact:
    email: "info@helikon.io"
  license:
    name: "GPL-3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
host: "78.181.100.160:17777"
basePath: "/report"
tags:
  - name: "era"
    description: "Single or multiple era reports."
  - name: "validator"
    description: "Single or multiple era-validator reports."
schemes:
  - "http"
paths:
  /era:
    get:
      tags:
        - "era"
      summary: "Get era(s) report"
      description: "Get era report for a single era or a range of eras."
      produces:
        - "application/json"
      operationId: "getEraReport"
      parameters:
        - name: "start_era_index"
          in: "query"
          description: "Index of the report start era."
          required: true
          type: "integer"
          format: "int32"
          minimum: 1
        - name: "end_era_index"
          in: "query"
          description: "Index of the report end era. Report is generated for single era if this field is null."
          required: false
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "Operation successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/EraReport"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
  /validator/{account_id_hex}:
    get:
      tags:
        - "validator"
      summary: "Get validator report for era(s)"
      description: "Get validator report over a single era or a range of eras."
      produces:
        - "application/json"
      operationId: "getValidatorReport"
      parameters:
        - name: "account_id_hex"
          in: "path"
          description: "Hex-encoded 32-byte account id of the validator, 0x-prefixed or not."
          required: true
          type: "string"
        - name: "start_era_index"
          in: "query"
          description: "Index of the report start era."
          required: true
          type: "integer"
          format: "int32"
          minimum: 1
        - name: "end_era_index"
          in: "query"
          description: "Index of the report end era (inclusive). Report is generated for single era if this field is null."
          required: false
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "Operation successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/EraValidatorReport"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Era:
    type: "object"
    properties:
      index:
        type: "integer"
        format: "int64"
      start_timestamp:
        type: "integer"
        format: "int64"
        description: "Era start timestamp in milliseconds."
      end_timestamp:
        type: "integer"
        format: "int64"
        description: "Era end timestamp in milliseconds."
  EraReport:
    type: "object"
    properties:
      era:
        $ref: "#/definitions/Era"
      minimum_stake:
        type: "integer"
        format: "int64"
        description: "Minimum stake backing a validator."
      maximum_stake:
        type: "integer"
        format: "int64"
        description: "Maximum stake backing a validator."
      average_stake:
        type: "integer"
        format: "int64"
        description: "Average of stakes backing all validators."
      median_stake:
        type: "integer"
        format: "int64"
        description: "Median of stakes backing all validators."
      total_validator_reward:
        type: "integer"
        format: "int64"
        description: "Total reward distributed to the validators in era."
      total_reward_points:
        type: "integer"
        format: "int64"
        description: "Total reward points earned in era by active validators."
      total_reward:
        type: "integer"
        format: "int64"
        description: "Total rewards distributed in era in native currency."
      total_stake:
        type: "integer"
        format: "int64"
        description: "Total amount staked by nominators/validators in era."
      active_nominator_count:
        type: "integer"
        format: "int64"
        description: "Number of active nominators in era."
      offline_offence_count:
        type: "integer"
        format: "int64"
        description: "Number of offline offences committed by the active validators in era."
      slashed_amount:
        type: "integer"
        format: "int64"
        description: "Total slashed amount in era."
      chilling_count:
        type: "integer"
        format: "int64"
        description: "Number of validator chilling events in era."
  EraValidatorReport:
    type: "object"
    properties:
      era:
        $ref: "#/definitions/Era"
      is_active:
        type: "boolean"
        description: "Whether the validator was active in era."
      commission_per_billion:
        type: "integer"
        format: "int64"
        description: "Validator commission per billion in era."
      self_stake:
        type: "integer"
        format: "int64"
        description: "Self stake of the validator in era."
      total_stake:
        type: "integer"
        format: "int64"
        description: "Total active stake of the validator in era."
      block_count:
        type: "integer"
        format: "int64"
        description: "Number of blocks authored by the validator in era."
      reward_points:
        type: "integer"
        format: "int64"
        description: "Reward points earned by the validator in era."
      self_reward:
        type: "integer"
        format: "int64"
        description: "Total amount earned by the validator in native token in era."
      staker_reward:
        type: "integer"
        format: "int64"
        description: "Total amount distributed to stakers in era."
      offline_offence_count:
        type: "integer"
        format: "int64"
        description: "Number of offline offences committed by the validator in era."
      slashed_amount:
        type: "integer"
        format: "int64"
        description: "Amount slashed from the validator in era."
      chilling_count:
        type: "integer"
        format: "int64"
        description: "Number of chilling events for the validator in era."
  Error:
    type: "object"
    required: [ "description" ]
    properties:
      description:
        type: "string"
        description: "Error description."