[package]
name = "subvt-service-common"
version = "0.8.2"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
actix-web = "4.1.0"
anyhow = "1.0"
async-trait = "0.1.56"
log = "0.4.16"
serde_json = "1.0"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.20", features = ["full"] }