[package]
name = "subvt-service-common"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
actix-web = "4.0.0-rc.2"
anyhow = "1.0.54"
async-trait = "0.1.52"
log = "0.4.14"
serde_json = "1.0.79"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.16" }
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-types = { path = "../subvt-types" }