[package]
name = "subvt-telemetry-processor"
version = "0.14.5"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
anyhow = "1.0"
async-lock = "2.5.0"
async-trait = "0.1"
async-tungstenite = { version = "0.18.0", features = ["tokio-runtime", "tokio-native-tls"] }
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.13"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.20", features = ["full"] }