[package]
name = "subvt-telemetry-processor"
version = "0.1.3"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.56"
async-lock = "2.5.0"
async-trait = "0.1.53"
async-tungstenite = { version = "0.17.2", features = ["tokio-runtime", "tokio-native-tls"] }
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.17.0", features = ["full"] }