[package]
name = "subvt-metrics"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
once_cell = "1.9.0"
prometheus = "0.13.0"
subvt-config = { path = "../subvt-config" }
thiserror = "1.0"
tokio = { version = "1.7.1", features = ["time", "rt-multi-thread"] }
warp = { version = "0.3.1", default-features = false }