[package]
name = "subvt-metrics"
version = "0.15.0"
edition = "2021"
rust-version = "1.67.0"

[dependencies]
env_logger = "0.10"
log = { workspace = true }
once_cell = "1"
prometheus = "0.13"
subvt-config = { path = "../subvt-config" }
thiserror = { workspace = true }
tokio = { version = "1.26", features = ["time", "rt-multi-thread"] }
warp = { version = "0.3", default-features = false }