[package]
name = "subvt-metrics"
version = "0.14.25"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
env_logger = "0.10.0"
log = { workspace = true }
once_cell = "1.13"
prometheus = "0.13.2"
subvt-config = { path = "../subvt-config" }
thiserror = { workspace = true }
tokio = { version = "1.20", features = ["time", "rt-multi-thread"] }
warp = { version = "0.3.2", default-features = false }