[common]
recovery_retry_seconds = 5

[substrate]
chain = "kusama"
chain_display = "Kusama"
# Kusama    0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE
# Polkadot  0x91B171BB158E2D3848FA23A9F1C25182FB8E20313B2C1EB49219DA7A70CE90C3
chain_genesis_hash = "0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE"
rpc_url = "wss://kusama-rpc.polkadot.io:443"
timeout_seconds = 30
connection_timeout_seconds = 30
request_timeout_seconds = 30
# for internal use, 1 for Kusama, 2 for Polkadot
network_id = 1
token_ticker = "KSM"
token_decimals = 12
token_format_decimal_points = 4

[log]
subvt_level = "debug"
other_level = "warn"

[rpc]
host = "0.0.0.0"
network_status_port = 7888
active_validator_list_port = 7889
inactive_validator_list_port = 7890
validator_details_port = 7891

[http]
host = "0.0.0.0"
report_service_port = 7900
app_service_port = 7901

[redis]
url = "redis://127.0.0.1:6379/"

[app_postgres]
host = "127.0.0.1"
port = 5432
username = "subvt"
password = "subvt"
database_name = "subvt_app"
pool_max_connections = 20
connection_timeout_seconds = 3

[network_postgres]
host = "127.0.0.1"
port = 5432
username = "subvt"
password = "subvt"
database_name = "subvt_network"
pool_max_connections = 20
connection_timeout_seconds = 3

[block_processor]
# min supported for Kusama is 4_401_243, metadata v12
# for Polkadot it is 2_005_673
# first block of 2021 for Kusama is 6_015_486
# first block of 2021 for Polkadot is 2_700_565
start_block_number = 6_015_486

[onekv]
# this many most recent records will always be kept in the database for reference
candidate_history_record_count = 5
candidate_list_endpoint = "https://kusama.w3f.community/candidates"
candidate_details_endpoint = "https://kusama.w3f.community/candidate/"
nominator_list_endpoint = "https://kusama.w3f.community/nominators"
refresh_seconds = 60
request_timeout_seconds = 60

[report]
max_era_index_range = 100

[telemetry]
# W3F       wss://telemetry.w3f.community/feed
# Polkadot  wss://feed.telemetry.polkadot.io/feed/
websocket_url = "wss://telemetry.w3f.community/feed"

[notification_generator]
unclaimed_payout_check_delay_hours = 1

[notification_sender]
sleep_millis = 2000
email_from = "SubVT Notifications <mail@host.com>"
email_reply_to = "noreply@host.com"
email_account = "mail@host.com"
email_password = "password"
email_smtp_server_url = "mail.host.com"
email_smtp_server_tls_port = 587
apns_key_location = "/path/to/key_file.p8"
apns_key_id = "KEY_ID_12345"
apns_team_id = "APNS_TEAM_ID"
apns_topic = "APP_BUNDLE"
apns_is_production = false
fcm_api_key = "FCM_API_KEY"
# can be set with the SUBVT_NOTIFICATION_SENDER__TELEGRAM_TOKEN
# environment variable
telegram_token = "TELEGRAM_TOKEN"
# can be set with the SUBVT_NOTIFICATION_SENDER__TEMPLATE_DIR_PATH
# environment variable
template_dir_path = "/path/to/the/template/dir"