version: "3.8"

services:
  subvt_app_service:
    container_name: subvt_app_service
    restart: unless-stopped
    image: "helikon/subvt-app-service:${VERSION}"
    networks:
      - subvt_app
    ports:
      - "${APP_SERVICE_PORT}:7901"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      - SUBVT__APP_POSTGRES__PORT=5432
  subvt_notification_processor:
    container_name: subvt_notification_processor
    restart: unless-stopped
    image: "helikon/subvt-notification-processor:${VERSION}"
    networks:
      - subvt_app
      - subvt_kusama
      - subvt_polkadot
    volumes:
      - ${CERT_DIR}:/subvt/cert
      - ${TEMPLATE_DIR}:/subvt/template
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      - SUBVT__APP_POSTGRES__PORT=5432
      # redis
      - SUBVT__REDIS__KUSAMA_URL=redis://subvt_kusama_redis:6379/
      - SUBVT__REDIS__POLKADOT_URL=redis://subvt_polkadot_redis:6379/
      # templates
      - SUBVT__NOTIFICATION_PROCESSOR__TEMPLATE_DIR_PATH=/subvt/template
      # telegram
      - SUBVT__NOTIFICATION_PROCESSOR__KUSAMA_TELEGRAM_API_TOKEN=${KUSAMA_TELEGRAM_API_TOKEN}
      - SUBVT__NOTIFICATION_PROCESSOR__POLKADOT_TELEGRAM_API_TOKEN=${POLKADOT_TELEGRAM_API_TOKEN}
      # APNS
      - SUBVT__NOTIFICATION_PROCESSOR__APNS_KEY_LOCATION=/subvt/cert/subvt_apns_key.p8
      - SUBVT__NOTIFICATION_PROCESSOR__APNS_KEY_ID=${APNS_KEY_ID}
      - SUBVT__NOTIFICATION_PROCESSOR__APNS_KEY_TEAM_ID=${APNS_KEY_TEAM_ID}
      - SUBVT__NOTIFICATION_PROCESSOR__APNS_TOPIC=${APNS_TOPIC}
      # FCM
      - SUBVT__NOTIFICATION_PROCESSOR__FCM_API_KEY=${FCM_API_KEY}
      # email
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_FROM=${EMAIL_FROM}
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_REPLY_TO=${EMAIL_REPLY_TO}
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_ACCOUNT={EMAIL_ACCOUNT}
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_SMTP_SERVER_URL=${EMAIL_SMTP_SERVER_URL}
      - SUBVT__NOTIFICATION_PROCESSOR__EMAIL_SMTP_SERVER_TLS_PORT=${EMAIL_SMTP_SERVER_TLS_PORT}
networks:
  subvt_app:
    name: subvt_app
  subvt_kusama:
    name: subvt_kusama
  subvt_polkadot:
    name: subvt_polkadot