version: "3.8"

services:
  subvt_kusama_block_processor:
    container_name: subvt_kusama_block_processor
    restart: unless-stopped
    image: "helikon/subvt-block-processor:0.1.3"
    networks:
      - subvt_kusama
    ports: [] # ["127.0.0.1:11000:11000"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=wss://kusama-rpc.polkadot.io:443
      # start block
      - SUBVT__BLOCK_PROCESSOR__START_BLOCK_NUMBER=12047800
  subvt_kusama_validator_list_updater:
    container_name: subvt_kusama_validator_list_updater
    restart: unless-stopped
    image: "helikon/subvt-validator-list-updater:0.1.3"
    depends_on:
      - subvt_kusama_block_processor
    networks:
      - subvt_kusama
    ports: [] # ["127.0.0.1:11001:11001"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=wss://kusama-rpc.polkadot.io:443
  subvt_kusama_active_validator_list_server:
    container_name: subvt_kusama_active_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-active-validator-list-server:0.1.3"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "127.0.0.1:7889:7889"
      # - "127.0.0.1:11003:11003"
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_inactive_validator_list_server:
    container_name: subvt_kusama_inactive_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-inactive-validator-list-server:0.1.3"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "127.0.0.1:7890:7890"
      # - "127.0.0.1:11004:11004"
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_validator_details_server:
    container_name: subvt_kusama_validator_details_server
    restart: unless-stopped
    image: "helikon/subvt-validator-details-server:0.1.3"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "127.0.0.1:7891:7891"
      # - "127.0.0.1:11002:11002"
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_network_status_updater:
    container_name: subvt_kusama_network_status_updater
    restart: unless-stopped
    image: "helikon/subvt-network-status-updater:0.1.3"
    networks:
      - subvt_kusama
    ports: [] # ["127.0.0.1:11005:11005"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=wss://kusama-rpc.polkadot.io:443
  subvt_kusama_network_status_server:
    container_name: subvt_kusama_network_status_server
    restart: unless-stopped
    image: "helikon/subvt-network-status-server:0.1.3"
    depends_on:
      - subvt_kusama_network_status_updater
    networks:
      - subvt_kusama
    ports:
      - "127.0.0.1:7888:7888"
      # - "127.0.0.1:11006:11006"
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_onekv_updater:
    container_name: subvt_kusama_onekv_updater
    restart: unless-stopped
    image: "helikon/subvt-onekv-updater:0.1.3"
    networks:
      - subvt_kusama
    ports: [] # ["127.0.0.1:11007:11007"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
  subvt_kusama_telemetry_processor:
    container_name: subvt_kusama_telemetry_processor
    restart: unless-stopped
    image: "helikon/subvt-telemetry-processor:0.1.3"
    networks:
      - subvt_kusama
    ports: [] # ["127.0.0.1:11008:11008"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
  subvt_kusama_notification_generator:
    container_name: subvt_kusama_notification_generator
    restart: unless-stopped
    image: "helikon/subvt-notification-generator:0.1.3"
    depends_on:
      - subvt_kusama_validator_list_updater
      - subvt_kusama_network_status_updater
    networks:
      - subvt_app
      - subvt_kusama
    ports: [] # ["127.0.0.1:11010:11010"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # app postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_report_service:
    container_name: subvt_kusama_report_service
    restart: unless-stopped
    image: "helikon/subvt-report-service:0.1.3"
    networks:
      - subvt_kusama
    ports:
      - "127.0.0.1:7900:7900"
      # - "127.0.0.1:11009:11009"
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
  subvt_kusama_telegram_bot:
    container_name: subvt_kusama_telegram_bot
    restart: unless-stopped
    image: "helikon/subvt-telegram-bot:0.1.3"
    networks:
      - subvt_app
      - subvt_kusama
    ports: [] # ["127.0.0.1:11012:11012"]
    environment:
      - SUBVT_ENV=production
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=debug
      # app postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # template dir
      - SUBVT__NOTIFICATION_PROCESSOR__TEMPLATE_DIR_PATH=/subvt/template
      # telegram
      - SUBVT__NOTIFICATION_PROCESSOR__TELEGRAM_TOKEN=TELEGRAM_TOKEN
      - SUBVT__TELEGRAM_BOT__ADMIN_CHAT_ID=1130952914
networks:
  subvt_kusama:
    name: subvt_kusama
  subvt_app:
    name: subvt_app