version: "3.8"

services:
  subvt_app_prometheus:
    container_name: subvt_app_prometheus
    restart: unless-stopped
    image: "prom/prometheus:v2.34.0"
    networks:
      - subvt_app
      - subvt_monitoring
    volumes:
      - /Users/kukabi/Documents/Development/subvt/subvt-backend/_prometheus/subvt-app-prometheus.yml:/etc/prometheus/prometheus.yml
  subvt_kusama_prometheus:
    container_name: subvt_kusama_prometheus
    restart: unless-stopped
    image: "prom/prometheus:v2.34.0"
    networks:
      - subvt_kusama
      - subvt_monitoring
    volumes:
      - /Users/kukabi/Documents/Development/subvt/subvt-backend/_prometheus/subvt-kusama-prometheus.yml:/etc/prometheus/prometheus.yml
  subvt_grafana:
    container_name: subvt_grafana
    restart: unless-stopped
    image: "grafana/grafana-oss:8.4.4"
    networks:
      - subvt_monitoring
    ports: [ "127.0.0.1:3000:3000" ]
networks:
  subvt_kusama:
    name: subvt_kusama
  subvt_app:
    name: subvt_app
  subvt_monitoring:
    name: subvt_monitoring