version: "3.8"

services:
  subvt_app_prometheus:
    container_name: subvt_app_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_app
      - subvt_monitoring
    volumes:
      - ${PROMETHEUS_DIR}/subvt-app-prometheus.yml:/etc/prometheus/prometheus.yml
  subvt_kusama_prometheus:
    container_name: subvt_kusama_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_kusama
      - subvt_monitoring
    volumes:
      - ${PROMETHEUS_DIR}/subvt-kusama-prometheus.yml:/etc/prometheus/prometheus.yml
  subvt_grafana:
    container_name: subvt_grafana
    restart: unless-stopped
    image: "grafana/grafana-oss:${GRAFANA_VERSION}"
    networks:
      - subvt_monitoring
    ports: [ "${GRAFANA_PORT}:3000" ]
networks:
  subvt_kusama:
    name: subvt_kusama
  subvt_app:
    name: subvt_app
  subvt_monitoring:
    name: subvt_monitoring