version: "3.8"

services:
  subvt_app_prometheus:
    container_name: subvt_app_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_app
      - subvt_monitoring
    ports:
      - "${APP_PROMETHEUS_PORT}:9090"
    volumes:
      - ${PROMETHEUS_DIR}/subvt-app-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_app_prometheus_data:/prometheus
  subvt_kusama_prometheus:
    container_name: subvt_kusama_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_kusama
      - subvt_monitoring
    ports:
      - "${KUSAMA_PROMETHEUS_PORT}:9090"
    volumes:
      - ${PROMETHEUS_DIR}/subvt-kusama-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_kusama_prometheus_data:/prometheus
  subvt_polkadot_prometheus:
    container_name: subvt_polkadot_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_polkadot
      - subvt_monitoring
    ports:
      - "${POLKADOT_PROMETHEUS_PORT}:9090"
    volumes:
      - ${PROMETHEUS_DIR}/subvt-polkadot-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_polkadot_prometheus_data:/prometheus
volumes:
  subvt_app_prometheus_data:
    name: subvt_app_prometheus_data
  subvt_kusama_prometheus_data:
    name: subvt_kusama_prometheus_data
  subvt_polkadot_prometheus_data:
    name: subvt_polkadot_prometheus_data
networks:
  subvt_app:
    name: subvt_app
  subvt_kusama:
    name: subvt_kusama
  subvt_polkadot:
    name: subvt_polkadot
  subvt_monitoring:
    name: subvt_monitoring