version: "3.8"

services:
  subvt_app_prometheus:
    container_name: subvt_app_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_app
      - subvt_monitoring
    volumes:
      - ${PROMETHEUS_DIR}/subvt-app-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_app_prometheus_data:/prometheus
  subvt_kusama_prometheus:
    container_name: subvt_kusama_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_kusama
      - subvt_monitoring
    volumes:
      - ${PROMETHEUS_DIR}/subvt-kusama-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_kusama_prometheus_data:/prometheus
  subvt_polkadot_prometheus:
    container_name: subvt_polkadot_prometheus
    restart: unless-stopped
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    networks:
      - subvt_polkadot
      - subvt_monitoring
    volumes:
      - ${PROMETHEUS_DIR}/subvt-polkadot-prometheus.yml:/etc/prometheus/prometheus.yml
      - subvt_polkadot_prometheus_data:/prometheus
  subvt_grafana:
    container_name: subvt_grafana
    restart: unless-stopped
    image: "grafana/grafana-oss:${GRAFANA_VERSION}"
    networks:
      - subvt_monitoring
    ports: [ "${GRAFANA_PORT}:3000" ]
    volumes:
      - subvt_grafana_data:/var/lib/grafana
volumes:
  subvt_app_prometheus_data:
    name: subvt_app_prometheus_data
  subvt_kusama_prometheus_data:
    name: subvt_kusama_prometheus_data
  subvt_polkadot_prometheus_data:
    name: subvt_polkadot_prometheus_data
  subvt_grafana_data:
    name: subvt_grafana_data
networks:
  subvt_app:
    name: subvt_app
  subvt_kusama:
    name: subvt_kusama
  subvt_polkadot:
    name: subvt_polkadot
  subvt_monitoring:
    name: subvt_monitoring