[package]
name = "subvt-types"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
chrono = { version = "0.4.19", default-features = true, features = ["serde"] }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.10" }
hex = "0.4"
pallet-identity = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.10" }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.10" }
parity-scale-codec = { version = "2.3.0", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.10" }
subvt-proc-macro = { path = "../subvt-proc-macro" }
subvt-utility = { path = "../subvt-utility" }