[package]
name = "subvt-telegram-bot"
version = "0.1.6"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
chrono = "0.4.19"
frankenstein = { version = "0.13.0", default-features = false, features = ["async-telegram-trait"] }
hyper = "0.14.18"
hyper-multipart-rfc7578 = "0.7.0"
hyper-tls = "0.5.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
regex = "1.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-governance = { path = "../subvt-governance" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-plotter = { path = "../subvt-plotter" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tera = "1.15.0"
thiserror = "1.0"
tokio = { version = "1.17.0", features = ["full"] }