[package]
name = "subvt-telegram-bot"
version = "0.8.2"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0"
async-recursion = "1.0.0"
async-trait = "0.1.56"
chrono = "0.4.19"
frankenstein = { version = "0.19", default-features = false, features = ["async-telegram-trait"] }
futures = "0.3.21"
hyper = "0.14"
hyper-multipart-rfc7578 = "0.8.0"
hyper-tls = "0.5.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.13"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subvt-config = { path = "../subvt-config" }
subvt-governance = { path = "../subvt-governance" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-nft = { path = "../subvt-nft" }
subvt-plotter = { path = "../subvt-plotter" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tera = "1.16.0"
thiserror = "1.0"
tokio = { version = "1.19.2",features = ["full"] }

[dev-dependencies]
mockall = "0.11.1"
mockito = "0.31.0"
rand = "0.8.5"