[package]
name = "subvt-telegram-bot"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.53"
async-trait = "0.1.52"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git", branch = "main" }
tera = "1.15.0"
tokio = { version = "1.17.0", features = ["full"] }