[package]
name = "subvt-substrate-client"
version = "0.1.7"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.57"
async-lock = "2.5.0"
blake2-rfc = { version = "0.2.18", default-features = false }
byteorder = { version = "1.4.3", default-features = false }
chrono = "0.4.19"
frame-metadata = { version = "15.0.0", features = ["std", "v12", "v13", "v14"] }
hex = "0.4"
jsonrpsee = { version = "0.11.0", features = ["full"] }
jsonrpsee-core = "0.11.0"
jsonrpsee-types = "0.11.0"
log = "0.4.16"
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
tokio = { version = "1.17.0", features = ["full"] }
twox-hash = { version = "1.6.2", features = ["digest_0_9"] }

[dev-dependencies]
hex = "0.4"
lazy_static = "1.4.0"
subvt-config = { path = "../subvt-config" }
tokio = { version = "1.17.0", features = ["full"] }