[package]
name = "subvt-substrate-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.51"
blake2-rfc = { version = "0.2.18", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
chrono = "0.4.19"
frame-metadata = { version = "14.2.0", features = ["std", "v12", "v13", "v14"] }
hex = "0.4"
jsonrpsee = { version = "0.6.1", features = ["full"] }
jsonrpsee-types = "0.6.1"
log = "0.4.14"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.14" }
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
twox-hash = { version = "1.6.0", features = ["digest_0_9"] }
