[package]
name = "subvt-substrate-client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
blake2-rfc = { version = "0.2.18", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
chrono = "0.4.19"
frame-metadata = { git = "https://github.com/paritytech/frame-metadata.git", branch = "main", features = ["std", "v13", "v12"] }
hex = "0.4"
jsonrpsee = { version = "0.3.1", features = ["full"] }
jsonrpsee-types = "0.3.1"
log = "0.4.14"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11" }
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }
subvt-utility = { path = "../subvt-utility" }
twox-hash = { version = "1.6.0", features = ["digest_0_9"] }
