[package]
name = "subvt-notification_generator"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.52"
async-lock = "2.4.0"
async-trait = "0.1.52"
chrono = { version = "0.4.19" }
config = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.14"
redis = "0.21.2"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
subvt-config = { path = "../subvt-config" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
subvt-persistence = { path = "../subvt-persistence" }
tokio = { version = "1.15.0", features = ["full"] }