[package]
name = "subvt-utility"
version = "0.1.9"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.57"
hex = "0.4"
num-format = "0.4.0"
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive", "full"] }