[package]
name = "subvt-onekv-updater"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
chrono = { version = "0.4.19", default-features = true, features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
prometheus = { version = "0.13.0", features = ["process"] }
reqwest = { version = "0.11.10", features = ["blocking", "json", "gzip", "brotli"] }
subvt-config = { path = "../subvt-config" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-persistence = { path = "../subvt-persistence" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-types = { path = "../subvt-types" }
subvt-logging = { path = "../subvt-logging" }
tokio = { version = "1.17.0", features = ["full"] }