[package]
name = "subvt-nft"
version = "0.1.7"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
anyhow = "1.0.56"
lazy_static = "1.4.0"
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["blocking", "json", "gzip", "brotli"] }
subvt-config = { path = "../subvt-config" }
subvt-types = { path = "../subvt-types" }