[package]
name = "subvt-network-status-updater"
version = "0.1.2"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
chrono = "0.4.19"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
redis = { version = "0.21.5", features = ["tokio-comp"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-metrics = { path = "../subvt-metrics" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.17.0", features = ["full"] }
