[package]
name = "subvt-network-status-updater"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
chrono = "0.4.19"
lazy_static = "1.4.0"
log = "0.4.14"
redis = "0.21.5"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.75"
subvt-config = { path = "../subvt-config" }
subvt-logging = { path = "../subvt-logging" }
subvt-service-common = { path = "../subvt-service-common" }
subvt-substrate-client = { path = "../subvt-substrate-client" }
subvt-types = { path = "../subvt-types" }
tokio = { version = "1.15.0", features = ["full"] }
