name: Format, Clippy and Tests

on:
  push:
    branches:
      - development
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-clippy-test:
    name: Format, Clippy and Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Docker network PostgreSQL
        run: docker run -d -t -p 15432:5432 helikon/subvt-network-postgres:0.6.3
      - name: Run Docker app PostgreSQL
        run: docker run -d -t -p 25432:5432 helikon/subvt-app-postgres:0.6.3
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly #-2022-03-14
          components: clippy, rustfmt
          override: true
      - run: rustup update
      - run: rustup update nightly #-2022-03-14
      - run: rustup default nightly #-2022-03-14
      - run: rustup target add wasm32-unknown-unknown --toolchain nightly #-2022-03-14
      - run: rustup default stable
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly #-2022-03-14
          command: clippy
          args: --all-targets -- -D warnings -W clippy::cognitive_complexity
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test